spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          google:
            client-id: 1048132687438-f8r49gt1h2atv1s9cmjjqievjiulu2ff.apps.googleusercontent.com
            client-secret: 5COUpkpr-AtppjIKpDld-gMA
            scope: profile,email
          naver:
            authorization-grant-type: authorization_code
            client-id: wlrrbioRlN97de7XMd24
            client-name: Naver
            client-secret: 99OigK3oVM
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: name,email,profile_image
